apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-operator-kustomization
  namespace: flux-system
spec:
  interval: 10m0s  # How frequently Flux checks for updates
  path: "../base/eck"  # Path to the source.yaml and eck-operator.yaml
  prune: true  # Ensures resources not in Git are deleted
  sourceRef:
    kind: GitRepository
    name: flux-system  # This is your Git repository where the YAML files are stored
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: elastic-operator
      namespace: elastic-system  # Monitors the health of the HelmRelease
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: elasticsearch
      namespace: elastic-stack  # Monitors the health of the HelmRelease
  dependsOn:
    - name: flux-system