apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: "../base/eck"  # Use the base for dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system