apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/eck/
patchesStrategicMerge:
  - | 
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: elasticsearch
      namespace: elastic-stack
    spec:
      values:
        eck-elasticsearch:
          nodeSets:
            - name: default
              volumeClaimTemplates:
                - metadata:
                    name: elasticsearch-data
                  spec:
                    resources:
                      requests:
                        storage: 100Gi  # Increase disk size to 100Gi for prod
        eck-kibana:
          spec:
            http:
              service:
                spec:
                  type: LoadBalancer  # Use LoadBalancer for prod
