apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  releaseName: eck-operator
  chart:
    spec:
      chart: eck-operator
      version: "2.14.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    createNamespace: true
    installCRDs: true
    elasticOperator:
      logLevel: info